import type { Product, Category } from "./types"

export const products: Product[] = [
  {
    id: 1,
    name: "Minimalist Wall Art Print",
    description: "Abstract geometric print in neutral tones, perfect for modern interiors.",
    images: [
      "/images/81ac7b2091538bc8e60fc55b5f93af7d.jpg",
      "/images/81ac7b2091538bc8e60fc55b5f93af7d.jpg",
      
    ],
    price: 890.99,
    category: "Wall Décor",
    trending: true,
    colors: ["Black", "White", "Beige"],
    availability: "In Stock",
    material: "Paper",
    dimensions: "50cm x 70cm",
    type: "Print",
  },
  {
    id: 2,
    name: "Ceramic Table Lamp",
    description: "Handcrafted ceramic lamp with linen shade, adding warm ambient lighting to any room.",
    images: [
      "/images/7253d5e8bb7eeb9ddb3ac0306c91a338.jpg",
     
    ],
    price: 1290.99,
    category: "Lighting",
    trending: true,
    colors: ["White", "Gray", "Terracotta"],
    availability: "In Stock",
    material: "Ceramic",
    dimensions: "30cm x 45cm",
    type: "Table Lamp",
  },
  {
    id: 3,
    name: "Woven Cotton Throw",
    description: "Soft, lightweight throw with subtle pattern, perfect for draping over sofas or beds.",
    images: [
      "/images/94122761468fab7fa75e512cd0200f46.jpg",

    ],
    price: 590.99,
    category: "Textiles & Soft Décor",
    trending: false,
    colors: ["Cream", "Gray", "Sage"],
    availability: "In Stock",
    material: "Cotton",
    dimensions: "130cm x 170cm",
    type: "Throw",
  },
  {
    id: 4,
    name: "Marble Accent Table",
    description: "Elegant side table with marble top and brass-finished metal base.",
    images: [
      "images/67534eab3432201edc8b915d4dafaa4c.jpg",
     
    ],
    price: 1990.99,
    category: "Furniture Accents",
    trending: true,
    colors: ["White/Brass", "Black/Brass"],
    availability: "In Stock",
    material: "Marble, Metal",
    dimensions: "45cm x 45cm x 50cm",
    type: "Side Table",
  },
  {
    id: 5,
    name: "Handblown Glass Vase",
    description: "Artisanal glass vase with organic shape, perfect for fresh or dried arrangements.",
    images: [
      "/images/a0c9cef616216d0dba1919af63a9f84d.jpg",

    ],
    price: 790.99,
    category: "Accessories & Small Décor",
    trending: true,
    colors: ["Clear", "Amber", "Blue"],
    availability: "In Stock",
    material: "Glass",
    dimensions: "15cm x 25cm",
    type: "Vase",
  },
  {
    id: 6,
    name: "Macramé Wall Hanging",
    description: "Handcrafted macramé wall art made from natural cotton rope.",
    images: [
      "/images/c1a49176244d78251fef93374aaba626.jpg",
      
    ],
    price: 690.99,
    category: "Wall Décor",
    trending: false,
    colors: ["Natural", "White"],
    availability: "In Stock",
    material: "Cotton",
    dimensions: "60cm x 90cm",
    type: "Wall Hanging",
  },
  {
    id: 7,
    name: "Brass Floor Lamp",
    description: "Modern floor lamp with adjustable arm and warm brass finish.",
    images: [
      "/images/product.jpg",
    ],
    price: 2490.99,
    category: "Lighting",
    trending: false,
    colors: ["Brass", "Black"],
    availability: "In Stock",
    material: "Brass, Steel",
    dimensions: "35cm x 150cm",
    type: "Floor Lamp",
  },
  {
    id: 8,
    name: "Hand-Knotted Wool Rug",
    description: "Premium wool rug with subtle geometric pattern, adding warmth and texture to any space.",
    images: [
      "/images/prodd.jpg",

    ],
    price: 399.99,
    category: "Textiles & Soft Décor",
    trending: true,
    colors: ["Ivory/Gray", "Blue/Gray"],
    availability: "In Stock",
    material: "Wool",
    dimensions: "200cm x 300cm",
    type: "Rug",
  },
  {
    id: 9,
    name: "Rattan Storage Basket",
    description: "Handwoven rattan basket, perfect for stylish storage solutions.",
    images: [
      "/images/prod.jpg",

    ],
    price: 49.99,
    category: "Accessories & Small Décor",
    trending: false,
    colors: ["Natural", "Black"],
    availability: "In Stock",
    material: "Rattan",
    dimensions: "40cm x 30cm x 25cm",
    type: "Storage",
  },
  {
    id: 10,
    name: "Velvet Accent Pillow",
    description: "Luxurious velvet pillow with piped edges, adding a touch of elegance to any seating area.",
    images: [
      "/images/f17febad16391a050a9fddfc1676c2fd.jpg",

    ],
    price: 39.99,
    category: "Textiles & Soft Décor",
    trending: false,
    colors: ["Emerald", "Navy", "Blush", "Gold"],
    availability: "In Stock",
    material: "Velvet",
    dimensions: "45cm x 45cm",
    type: "Pillow",
  },
  {
    id: 11,
    name: "Wooden Wall Shelf",
    description: "Floating shelf crafted from solid wood with hidden mounting hardware.",
    images: [
      "/images/fe34083dde17ef7f95d94c85c7637324.jpg",
      
    ],
    price: 89.99,
    category: "Wall Décor",
    trending: false,
    colors: ["Oak", "Walnut", "Black"],
    availability: "In Stock",
    material: "Wood",
    dimensions: "80cm x 20cm x 4cm",
    type: "Shelf",
  },
  {
    id: 12,
    name: "Ceramic Planter Set",
    description: "Set of three ceramic planters in complementary sizes and textures.",
    images: [
      "/images/e9a7ab63c6ec382278b1d7d17de20548.jpg",
      

    ],
    price: 69.99,
    category: "Accessories & Small Décor",
    trending: true,
    colors: ["White", "Gray", "Terracotta"],
    availability: "In Stock",
    material: "Ceramic",
    dimensions: "Various sizes",
    type: "Planter",
  },
  {
    id: 13,
    name: "Minimalist Desk Chair",
    description: "Sleek, ergonomic desk chair with clean lines and comfortable support.",
    images: [
      "/images/e17aa5a02f66e8cdae3625e9d36b05c6.jpg",


    ],
    price: 199.99,
    category: "Furniture Accents",
    trending: true,
    colors: ["Black", "Gray", "White"],
    availability: "In Stock",
    material: "Metal, Fabric",
    dimensions: "60cm x 55cm x 85cm",
    type: "Chair",
  },
  {
    id: 14,
    name: "Pendant Light Fixture",
    description: "Modern pendant light with adjustable height and warm illumination.",
    images: [
      "/images/dbcf9057a81bf38faa1dcdfc0350c37d.jpg",
 
    ],
    price: 149.99,
    category: "Lighting",
    trending: false,
    colors: ["Black", "Brass", "Copper"],
    availability: "In Stock",
    material: "Metal, Glass",
    dimensions: "30cm diameter",
    type: "Pendant",
  },
  {
    id: 15,
    name: "Linen Curtain Panel",
    description: "Light-filtering linen curtain that adds texture and privacy to any room.",
    images: [
      "/images/d60c26ce36bfbf16521ce0e378002bd2.jpg",

    ],
    price: 79.99,
    category: "Textiles & Soft Décor",
    trending: false,
    colors: ["White", "Natural", "Gray", "Navy"],
    availability: "In Stock",
    material: "Linen",
    dimensions: "140cm x 240cm",
    type: "Curtain",
  },
  {
    id: 16,
    name: "Marble Bookends",
    description: "Elegant marble bookends that add sophistication to your shelves.",
    images: [
      "/images/cf5949242768ba7998c841b45bfbfae6.jpg",
     
    ],
    price: 59.99,
    category: "Accessories & Small Décor",
    trending: false,
    colors: ["White", "Black", "Green"],
    availability: "In Stock",
    material: "Marble",
    dimensions: "10cm x 8cm x 15cm",
    type: "Bookend",
  },
  {
    id: 17,
    name: "Wooden Coffee Table",
    description: "Minimalist coffee table with solid wood construction and sleek design.",
    images: [
      "/images/ce55a34a606a79a856777b5e4347d805.jpg",

    ],
    price: 299.99,
    category: "Furniture Accents",
    trending: false,
    colors: ["Oak", "Walnut", "Black"],
    availability: "In Stock",
    material: "Wood",
    dimensions: "120cm x 60cm x 40cm",
    type: "Table",
  },
  {
    id: 18,
    name: "Framed Abstract Art",
    description: "Contemporary abstract artwork in a minimalist frame, perfect for modern spaces.",
    images: [
      "/images/c1a49176244d78251fef93374aaba626.jpg",
     
    ],
    price: 129.99,
    category: "Wall Décor",
    trending: true,
    colors: ["Multicolor"],
    availability: "In Stock",
    material: "Paper, Wood Frame",
    dimensions: "60cm x 80cm",
    type: "Art",
  },
]

export const categories: Category[] = [
  {
    name: "Wall Décor",
    image: "/images/1e98c427c9f2b39d23000c7c03457d07.jpg",
    description: "Find the perfect piece to enhance your walls.",
    items: "Mirrors • Prints • Wall Art • Shelves",
    slug: "wall-decor",
  },
  {
    name: "Lighting",
    image: "/images/1f138118d5dac98d61bbab85c275170d.jpg",
    description: "Illuminate your space with style.",
    items: "Table Lamps • Floor Lamps • Pendants • Sconces",
    slug: "lighting",
  },
  {
    name: "Textiles",
    image: "/images/4ecbc08f1a737a3336b29201486b5055.jpg",
    description: "Add comfort and texture to any room.",
    items: "Pillows • Throws • Rugs • Curtains",
    slug: "textiles",
  },
  {
    name: "Furniture",
    image: "/images/5d72e37b90e24dd6f0af319d8aa3d464.jpg",
    description: "Statement pieces for every space.",
    items: "Chairs • Tables • Sofas • Storage",
    slug: "furniture",
  },
  {
    name: "Accessories",
    image: "/images/8beec0ba2ec807a13bf06daf43785716.jpg",
    description: "The finishing touches for your home.",
    items: "Vases • Candles • Decorative Objects • Planters",
    slug: "accessories",
  },
  {
    name: "Kitchen",
    image: "/images/8bf3717565d3886761141795cf467669.jpg",
    description: "Elevate your culinary space.",
    items: "Dinnerware • Serveware • Utensils • Linens",
    slug: "kitchen",
  },
  {
    name: "Bath",
    image: "/images/9b07a35d8aee3e8cafcc991b77783f3f.jpg",
    description: "Transform your bathroom into a sanctuary.",
    items: "Towels • Bath Accessories • Shower Curtains • Storage",
    slug: "bath",
  },
  {
    name: "Outdoor",
    image: "/images/9e8654292771107b84e64e82d2ee674b.jpg",
    description: "Extend your style to outdoor spaces.",
    items: "Planters • Furniture • Lighting • Décor",
    slug: "outdoor",
  },
  {
    name: "Seasonal",
    image: "/images/27b1db69f0db2baa4b4810886ee51049.jpg",
    description: "Celebrate the seasons with style.",
    items: "Holiday • Spring • Summer • Fall • Winter",
    slug: "seasonal",
  },
]

export const productTypes = [
  "All",
  "Art",
  "Bookend",
  "Chair",
  "Curtain",
  "Floor Lamp",
  "Pendant",
  "Pillow",
  "Planter",
  "Print",
  "Rug",
  "Shelf",
  "Side Table",
  "Storage",
  "Table",
  "Table Lamp",
  "Throw",
  "Vase",
  "Wall Hanging",
]

export const materials = [
  "All",
  "Brass",
  "Ceramic",
  "Cotton",
  "Fabric",
  "Glass",
  "Linen",
  "Marble",
  "Metal",
  "Paper",
  "Rattan",
  "Steel",
  "Velvet",
  "Wood",
  "Wool",
]

export const colorOptions = [
  "All",
  "Amber",
  "Beige",
  "Black",
  "Blue",
  "Blush",
  "Brass",
  "Clear",
  "Copper",
  "Cream",
  "Emerald",
  "Gold",
  "Gray",
  "Green",
  "Ivory",
  "Natural",
  "Navy",
  "Oak",
  "Sage",
  "Terracotta",
  "Walnut",
  "White",
]

export const priceRanges = ["All", "Under $50", "$50 - $100", "$100 - $200", "$200 - $300", "$300 - $400", "Over $400"]

export const sortOptions = ["Featured", "Price: Low to High", "Price: High to Low", "Newest", "Bestselling"]
